"""add_groups_column

Revision ID: 099b54a32f76
Revises: dd02f0f0dc07
Create Date: 2026-04-20 14:18:32.061209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '099b54a32f76'
down_revision: Union[str, Sequence[str], None] = 'dd02f0f0dc07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('groups', sa.ARRAY(sa.String(length=6)), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'groups')
    # ### end Alembic commands ###
