"""add_groups_column

Revision ID: 19828d1283bb
Revises: 099b54a32f76
Create Date: 2026-04-20 14:25:09.586603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19828d1283bb'
down_revision: Union[str, Sequence[str], None] = '099b54a32f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE surveys SET groups = ARRAY['3341'] WHERE groups IS NULL")
    op.alter_column('surveys', 'groups',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=6)),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('surveys', 'groups',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=6)),
               nullable=True)
    # ### end Alembic commands ###
