export { HomePage } from './HomePage'
export { SurveyPassingPage } from './SurveyPassingPage'
export { SurveyResultPage } from './SurveyResultPage' 
export { DashBoardPage } from './DashBoardPage'
export { HealthPage } from './HealthPage'